AllCops:
  # Rubyバージョン指定
  TargetRubyVersion: 2.6

  DisabledByDefault: true
  # 除外
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
    - node_modules/**/*

  # gemをA~Zに並び替え
  Bundler/OrderedGems:
    Enabled: true

  # 最後の行に空白行を入れる
  Layout/EmptyLines:
    Enabled: true

  # 余計な空白行を削除
  Layout/TrailingEmptyLines:
    Enables: true

  Layout/TrailingWhitespace:
    Enables: true

  Style/MethodDefParentheses:
    Enables: true

  Style/StringLiterals:
    EnforcedStyle: single_quotes

  Style/StringLiteralsInInterpolation:
    EnforcedStyle: single_quotes


# 日本語でのコメントを許可
# AsciiComments:
#   Enabled: false

# クラスのコメント必須を無視
# Documentation:
#   Enabled: false

# モジュール名::クラス名の定義を許可
# ClassAndModuleChildren:
#   Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
# Style/FrozenStringLiteralComment:
#   Enabled: false